import Head from 'next/head'
import Homepage from '../components/Homepage'
import { Inter } from '@next/font/google'
import Midpage from '../components/Midpage'







const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>code-c</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <Homepage heading='home of {clean code}'
            
            message='Trusted by 7 million developers,
            Code-c helps you build high-quality code quickly and systematically.'/>
      <Midpage/>
      
      
    </>
  )
}
